[workspace]
members = [
    ".",
    "tests/mysql_sakila",
]

[package]
name = "sea-schema"
version = "0.1.0"
authors = [ "Chris Tsang <tyt2y7@gmail.com>" ]
edition = "2018"
description = "A schema discovery and conversion tool"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/sea-schema"
repository = "https://github.com/SeaQL/sea-schema"
categories = [ "database" ]
keywords = [ "database", "sql", "mysql", "postgres" ]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lib]
name = "sea_schema"
path = "src/lib.rs"

[dependencies]
sea-query = { version = "0.8" }